---
kind: Service
apiVersion: v1
metadata:
   name: service-example
spec: 
  ports:
    - name: jenkins
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: jenkins
  type: LoadBalancer